- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    #- index_recovery
    #- index_summary
    - shard
    #- ml_job
  period: 10s
  hosts: ["http://es01:9200","http://es02:9200","http://es03:9200"]
  enabled: true
  #username: "elastic"
  #password: "changeme"
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Set to false to fetch all entries
  #index_recovery.active_only: true

  # Set to true to send data collected by module to X-Pack
  # Monitoring instead of metricbeat-* indices.
  #xpack.enabled: fa